# Default values for retropos-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  replicas: 5
  aadpodidbinding: kubernetes.azureidentity
  name: consumer-function
  dapr:
    name: consumer-function
    config: dapr.tracing
  containerName: consumer-function
  image:
    repository: 
    pullPolicy: Always
  env:
    azureWebJobsStorage: 
    serviceBusConnectionString: 
    consumerStateComponentName: dapr.state.consumer-state
  resources:
    requests:
      memory: "200Mi"
      cpu: "150m"
    limits:
      memory: "300Mi"
      cpu: "200m"
keda:
  triggerAuthentication:
    name: keda.triggerauthentication.consumer-function
  scaledObject:
    name: keda.scaledobject.consumer-function
    deploymentName: consumer-function
    pollingInterval: 5
    coolDownPeriod: 0
    minReplicaCount: 5
    maxReplicaCount: 20
    triggers:
      type: azure-servicebus
      queueName: internal-queue
      messageCount: 2
      authenticationRef: keda.triggerauthentication.consumer-function
secretProviderClass:
  name: kubernetes.secretproviderclass.keyvault