# Default values for retropos-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

secretProviderClass:
  name: kubernetes.secretproviderclass.keyvault
  keyVaultName:
  resourceGroup:
  subscriptionId:
  tenantId:
  databaseConnectionString:
  databasePrimaryKey:
  serviceBusConnectionString:
  storageConnectionString:

exposedAPI:
  deployment:
    replicas: 2
    aadpodidbinding: kubernetes.azureidentity
    name: exposed-api
    dapr:
      name: exposed-api
      config: dapr.tracing
    containerName: exposed-api
    image:
      repository:
      pullPolicy: Always 
    env:
      outputBindingComponentName: dapr.binding.internal-queue
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "150Mi"
      cpu: "150m"
  service:
    name: exposed-api
    type: LoadBalancer
  autoscaling:
    name: exposed-api
    minReplicas: 2
    maxReplicas: 20
    targetCPUUtilizationPercentage: 40
    targetMemoryUtilizationPercentage: 40

consumerAPI:
  deployment:
    replicas: 5
    aadpodidbinding: kubernetes.azureidentity
    name: consumer-api
    dapr:
      name: consumer-api
      config: dapr.tracing
    containerName: consumer-api
    image:
      repository:
      pullPolicy: Always
    env:
      azureWebJobsStorage:
      serviceBusConnectionString:
      consumerStateComponentName: dapr.state.consumer-state
    resources:
      requests:
        memory: "200Mi"
        cpu: "150m"
      limits:
        memory: "300Mi"
        cpu: "200m"
  keda:
    triggerAuthentication:
      name: keda.triggerauthentication.consumer-api
    scaledObject:
      name: keda.scaledobject.consumer-api
      deploymentName: consumer-api
      pollingInterval: 5
      coolDownPeriod: 0
      minReplicaCount: 5
      maxReplicaCount: 20
      triggers:
        type: azure-servicebus
        queueName: internal-queue
        messageCount: 2
        authenticationRef: keda.triggerauthentication.consumer-api